################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-present Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

PKG_NAME="procps-ng"
PKG_VERSION="3.3.12"
PKG_ARCH="any"
PKG_LICENSE="GPL"
PKG_SITE="https://gitlab.com/procps-ng/procps"
PKG_URL="$SOURCEFORGE_SRC/$PKG_NAME/Production/$PKG_NAME-$PKG_VERSION.tar.xz"
PKG_DEPENDS_TARGET="toolchain netbsd-curses"
PKG_SECTION="tools"
PKG_SHORTDESC="Command line and full screen utilities for browsing procfs"
PKG_LONGDESC="Command line and full screen utilities for browsing procfs, a "pseudo" file system dynamically generated by the kernel to provide information about the status of entries in its process table."
PKG_AUTORECONF="no"

PKG_CONFIGURE_OPTS_TARGET="ac_cv_func_malloc_0_nonnull=yes \
                           ac_cv_func_realloc_0_nonnull=yes \
                           --disable-shared \
                           --enable-static \
                           --enable-wide-percent \
                           --disable-pidof \
                           --disable-kill"

PROCPS_EXCLUDE_BIN="pgrep  pkill  pmap  pwdx  slabtop  tload  uptime  vmstat  w  watch"

post_makeinstall_target() {
# cleanup
  rm -rf $INSTALL/usr/sbin
  for i in $PROCPS_EXCLUDE_BIN; do
    rm -rf $INSTALL/usr/bin/$i
  done
}
