#!/bin/bash
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-present Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

. config/options $1

if [ -z "$2" ]; then
  echo "usage: $0 package_name target_dir"
  exit 1
fi

[ -z "$PKG_URL" -o -z "$PKG_SOURCE_NAME" ] && exit 1
[ ! -d "$SOURCES/$1" -o ! -d "$2" ] && exit 1

for pattern in .tar.gz .tar.xz .tar.bz2 .tgz .txz .tbz .7z .zip; do
  if [[ $PKG_SOURCE_NAME =~ ${pattern//./\\.}$ ]]; then
    f="$SOURCES/$1/$PKG_SOURCE_NAME"
    if [ ! -f $f ]; then
      echo "error: File $PKG_SOURCE_NAME doesn't exist in package $1 sources directory"
      echo "Have you called scripts/extract before scripts/get ?"
      exit 1
    fi
    case $PKG_SOURCE_NAME in
      *.tar)
        tar xf $f -C $2
        ;;
      *.tar.bz2 | *.tbz)
        tar xjf $f -C $2
        ;;
      *.tar.gz | *.tgz)
        tar xzf $f -C $2
        ;;
      *.tar.xz | *.txz)
        tar xJf $f -C $2
        ;;
      *.7z)
        mkdir -p $2/$1
        7z x -o$2/$1 $f
        ;;
      *.zip)
        unzip -q $f -d $2
        ;;
      *.diff | *.patch)
        cat $f | patch -d $2 -p1
        ;;
      *.diff.bz2 | *.patch.bz2 | patch-*.bz2)
        bzcat $f | patch -d $2 -p1
        ;;
      *.diff.gz | *.patch.gz | patch-*.gz)
        zcat $f | patch -d $2 -p1
        ;;
      *)
        cp -pPR $f $2
        ;;
    esac
    break
  fi
done
